// SPDX-License-Identifier: MPL-2.0
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.localhold.localhold_key_bridge

import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object KeyBridgeMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  @Suppress("UNUSED_PARAMETER")
  fun wrapError(exception: Throwable): List<Any?> {
    return listOf("internalFailure", null, null)
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class KeyBridgeErrorCode(val raw: Int) {
  INVALID_REQUEST(0),
  INVALID_CREDENTIALS(1),
  UNSUPPORTED_VERSION(2),
  SESSION_NOT_FOUND(3),
  SESSION_LOCKED(4),
  REAUTHENTICATION_REQUIRED(5),
  INTEGRITY_FAILURE(6),
  PAYLOAD_TOO_LARGE(7),
  PLATFORM_UNAVAILABLE(8),
  BIOMETRIC_UNAVAILABLE(9),
  BIOMETRIC_INVALIDATED(10),
  INTERNAL_FAILURE(11);

  companion object {
    fun ofRaw(raw: Int): KeyBridgeErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformFeatureErrorCode(val raw: Int) {
  INVALID_REQUEST(0),
  PERMISSION_DENIED(1),
  PERMISSION_RESTRICTED(2),
  NOT_FOUND(3),
  PLATFORM_UNAVAILABLE(4),
  INTERNAL_FAILURE(5);

  companion object {
    fun ofRaw(raw: Int): PlatformFeatureErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NotificationPermissionCode(val raw: Int) {
  NOT_DETERMINED(0),
  DENIED(1),
  RESTRICTED(2),
  AUTHORIZED(3);

  companion object {
    fun ofRaw(raw: Int): NotificationPermissionCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WallClockResolutionCode(val raw: Int) {
  UNIQUE(0),
  EARLIER(1),
  LATER(2),
  GAP_ADJUSTED(3);

  companion object {
    fun ofRaw(raw: Int): WallClockResolutionCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ShareKindCode(val raw: Int) {
  TEXT(0),
  URL(1),
  FILE(2),
  IMAGE(3);

  companion object {
    fun ofRaw(raw: Int): ShareKindCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateVaultKeyRequest (
  val vaultId: String,
  val masterPassword: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateVaultKeyRequest {
      val vaultId = pigeonVar_list[0] as String
      val masterPassword = pigeonVar_list[1] as ByteArray
      return CreateVaultKeyRequest(vaultId, masterPassword)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vaultId,
      masterPassword,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateVaultKeyRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultId, other.vaultId) && KeyBridgeMessagesPigeonUtils.deepEquals(this.masterPassword, other.masterPassword)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultId)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.masterPassword)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenVaultSessionRequest (
  val vaultId: String,
  val masterPassword: ByteArray,
  val vaultKeyEnvelope: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenVaultSessionRequest {
      val vaultId = pigeonVar_list[0] as String
      val masterPassword = pigeonVar_list[1] as ByteArray
      val vaultKeyEnvelope = pigeonVar_list[2] as ByteArray
      return OpenVaultSessionRequest(vaultId, masterPassword, vaultKeyEnvelope)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vaultId,
      masterPassword,
      vaultKeyEnvelope,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenVaultSessionRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultId, other.vaultId) && KeyBridgeMessagesPigeonUtils.deepEquals(this.masterPassword, other.masterPassword) && KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultKeyEnvelope, other.vaultKeyEnvelope)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultId)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.masterPassword)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultKeyEnvelope)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RewrapVaultKeyRequest (
  val sessionHandle: String,
  val newMasterPassword: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RewrapVaultKeyRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val newMasterPassword = pigeonVar_list[1] as ByteArray
      return RewrapVaultKeyRequest(sessionHandle, newMasterPassword)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      newMasterPassword,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RewrapVaultKeyRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.newMasterPassword, other.newMasterPassword)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.newMasterPassword)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EncryptPayloadRequest (
  val sessionHandle: String,
  val plaintext: ByteArray,
  val authenticatedData: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EncryptPayloadRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val plaintext = pigeonVar_list[1] as ByteArray
      val authenticatedData = pigeonVar_list[2] as ByteArray
      return EncryptPayloadRequest(sessionHandle, plaintext, authenticatedData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      plaintext,
      authenticatedData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EncryptPayloadRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.plaintext, other.plaintext) && KeyBridgeMessagesPigeonUtils.deepEquals(this.authenticatedData, other.authenticatedData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.plaintext)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.authenticatedData)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptPayloadRequest (
  val sessionHandle: String,
  val encryptedPayload: ByteArray,
  val authenticatedData: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptPayloadRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val encryptedPayload = pigeonVar_list[1] as ByteArray
      val authenticatedData = pigeonVar_list[2] as ByteArray
      return DecryptPayloadRequest(sessionHandle, encryptedPayload, authenticatedData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      encryptedPayload,
      authenticatedData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DecryptPayloadRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.encryptedPayload, other.encryptedPayload) && KeyBridgeMessagesPigeonUtils.deepEquals(this.authenticatedData, other.authenticatedData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.encryptedPayload)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.authenticatedData)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VaultSessionReply (
  val sessionHandle: String? = null,
  val keyGenerationId: String? = null,
  val vaultKeyEnvelope: ByteArray? = null,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VaultSessionReply {
      val sessionHandle = pigeonVar_list[0] as String?
      val keyGenerationId = pigeonVar_list[1] as String?
      val vaultKeyEnvelope = pigeonVar_list[2] as ByteArray?
      val error = pigeonVar_list[3] as KeyBridgeErrorCode?
      return VaultSessionReply(sessionHandle, keyGenerationId, vaultKeyEnvelope, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      keyGenerationId,
      vaultKeyEnvelope,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VaultSessionReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.keyGenerationId, other.keyGenerationId) && KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultKeyEnvelope, other.vaultKeyEnvelope) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.keyGenerationId)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultKeyEnvelope)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PayloadReply (
  val payload: ByteArray? = null,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayloadReply {
      val payload = pigeonVar_list[0] as ByteArray?
      val error = pigeonVar_list[1] as KeyBridgeErrorCode?
      return PayloadReply(payload, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PayloadReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.payload, other.payload) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.payload)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StatusReply (
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusReply {
      val error = pigeonVar_list[0] as KeyBridgeErrorCode?
      return StatusReply(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatusReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecoveryCeremonyReply (
  val ceremonyHandle: String? = null,
  val challengePositions: List<Long>? = null,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecoveryCeremonyReply {
      val ceremonyHandle = pigeonVar_list[0] as String?
      val challengePositions = pigeonVar_list[1] as List<Long>?
      val error = pigeonVar_list[2] as KeyBridgeErrorCode?
      return RecoveryCeremonyReply(ceremonyHandle, challengePositions, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ceremonyHandle,
      challengePositions,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecoveryCeremonyReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.ceremonyHandle, other.ceremonyHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.challengePositions, other.challengePositions) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.ceremonyHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.challengePositions)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfirmRecoveryKeyRequest (
  val ceremonyHandle: String,
  val challengeWordsUtf8: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfirmRecoveryKeyRequest {
      val ceremonyHandle = pigeonVar_list[0] as String
      val challengeWordsUtf8 = pigeonVar_list[1] as ByteArray
      return ConfirmRecoveryKeyRequest(ceremonyHandle, challengeWordsUtf8)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ceremonyHandle,
      challengeWordsUtf8,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConfirmRecoveryKeyRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.ceremonyHandle, other.ceremonyHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.challengeWordsUtf8, other.challengeWordsUtf8)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.ceremonyHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.challengeWordsUtf8)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenVaultWithRecoveryRequest (
  val vaultId: String,
  val recoveryPhraseUtf8: ByteArray,
  val recoveryKeyEnvelope: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenVaultWithRecoveryRequest {
      val vaultId = pigeonVar_list[0] as String
      val recoveryPhraseUtf8 = pigeonVar_list[1] as ByteArray
      val recoveryKeyEnvelope = pigeonVar_list[2] as ByteArray
      return OpenVaultWithRecoveryRequest(vaultId, recoveryPhraseUtf8, recoveryKeyEnvelope)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vaultId,
      recoveryPhraseUtf8,
      recoveryKeyEnvelope,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenVaultWithRecoveryRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultId, other.vaultId) && KeyBridgeMessagesPigeonUtils.deepEquals(this.recoveryPhraseUtf8, other.recoveryPhraseUtf8) && KeyBridgeMessagesPigeonUtils.deepEquals(this.recoveryKeyEnvelope, other.recoveryKeyEnvelope)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultId)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.recoveryPhraseUtf8)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.recoveryKeyEnvelope)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SensitiveClipboardRequest (
  val utf8Value: ByteArray,
  val expirySeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SensitiveClipboardRequest {
      val utf8Value = pigeonVar_list[0] as ByteArray
      val expirySeconds = pigeonVar_list[1] as Long
      return SensitiveClipboardRequest(utf8Value, expirySeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      utf8Value,
      expirySeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SensitiveClipboardRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.utf8Value, other.utf8Value) && KeyBridgeMessagesPigeonUtils.deepEquals(this.expirySeconds, other.expirySeconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.utf8Value)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.expirySeconds)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricStatusReply (
  val configured: Boolean,
  val invalidated: Boolean,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricStatusReply {
      val configured = pigeonVar_list[0] as Boolean
      val invalidated = pigeonVar_list[1] as Boolean
      val error = pigeonVar_list[2] as KeyBridgeErrorCode?
      return BiometricStatusReply(configured, invalidated, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configured,
      invalidated,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BiometricStatusReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.configured, other.configured) && KeyBridgeMessagesPigeonUtils.deepEquals(this.invalidated, other.invalidated) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.configured)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.invalidated)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FeatureStatusReply (
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FeatureStatusReply {
      val error = pigeonVar_list[0] as PlatformFeatureErrorCode?
      return FeatureStatusReply(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FeatureStatusReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationPermissionReply (
  val state: NotificationPermissionCode,
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationPermissionReply {
      val state = pigeonVar_list[0] as NotificationPermissionCode
      val error = pigeonVar_list[1] as PlatformFeatureErrorCode?
      return NotificationPermissionReply(state, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationPermissionReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.state, other.state) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LauncherActionReply (
  val actionCode: Long,
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LauncherActionReply {
      val actionCode = pigeonVar_list[0] as Long
      val error = pigeonVar_list[1] as PlatformFeatureErrorCode?
      return LauncherActionReply(actionCode, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      actionCode,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LauncherActionReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.actionCode, other.actionCode) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.actionCode)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallClockRequest (
  val year: Long,
  val month: Long,
  val day: Long,
  val hour: Long,
  val minute: Long,
  val timeZoneId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallClockRequest {
      val year = pigeonVar_list[0] as Long
      val month = pigeonVar_list[1] as Long
      val day = pigeonVar_list[2] as Long
      val hour = pigeonVar_list[3] as Long
      val minute = pigeonVar_list[4] as Long
      val timeZoneId = pigeonVar_list[5] as String
      return WallClockRequest(year, month, day, hour, minute, timeZoneId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      year,
      month,
      day,
      hour,
      minute,
      timeZoneId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WallClockRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.year, other.year) && KeyBridgeMessagesPigeonUtils.deepEquals(this.month, other.month) && KeyBridgeMessagesPigeonUtils.deepEquals(this.day, other.day) && KeyBridgeMessagesPigeonUtils.deepEquals(this.hour, other.hour) && KeyBridgeMessagesPigeonUtils.deepEquals(this.minute, other.minute) && KeyBridgeMessagesPigeonUtils.deepEquals(this.timeZoneId, other.timeZoneId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.year)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.month)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.day)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.hour)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.minute)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.timeZoneId)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallClockReply (
  val utcEpochMilliseconds: Long,
  val resolution: WallClockResolutionCode,
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallClockReply {
      val utcEpochMilliseconds = pigeonVar_list[0] as Long
      val resolution = pigeonVar_list[1] as WallClockResolutionCode
      val error = pigeonVar_list[2] as PlatformFeatureErrorCode?
      return WallClockReply(utcEpochMilliseconds, resolution, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      utcEpochMilliseconds,
      resolution,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WallClockReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.utcEpochMilliseconds, other.utcEpochMilliseconds) && KeyBridgeMessagesPigeonUtils.deepEquals(this.resolution, other.resolution) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.utcEpochMilliseconds)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.resolution)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SafeReminderRequest (
  val syntheticId: String,
  val utcEpochMilliseconds: Long,
  val privacyCode: Long,
  val safeName: String? = null,
  val safeAmount: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SafeReminderRequest {
      val syntheticId = pigeonVar_list[0] as String
      val utcEpochMilliseconds = pigeonVar_list[1] as Long
      val privacyCode = pigeonVar_list[2] as Long
      val safeName = pigeonVar_list[3] as String?
      val safeAmount = pigeonVar_list[4] as String?
      return SafeReminderRequest(syntheticId, utcEpochMilliseconds, privacyCode, safeName, safeAmount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      syntheticId,
      utcEpochMilliseconds,
      privacyCode,
      safeName,
      safeAmount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SafeReminderRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.syntheticId, other.syntheticId) && KeyBridgeMessagesPigeonUtils.deepEquals(this.utcEpochMilliseconds, other.utcEpochMilliseconds) && KeyBridgeMessagesPigeonUtils.deepEquals(this.privacyCode, other.privacyCode) && KeyBridgeMessagesPigeonUtils.deepEquals(this.safeName, other.safeName) && KeyBridgeMessagesPigeonUtils.deepEquals(this.safeAmount, other.safeAmount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.syntheticId)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.utcEpochMilliseconds)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.privacyCode)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.safeName)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.safeAmount)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InboundShareDescriptorReply (
  val id: String,
  val kind: ShareKindCode,
  val byteLength: Long,
  val receivedUtcEpochMilliseconds: Long,
  val expiresUtcEpochMilliseconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboundShareDescriptorReply {
      val id = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as ShareKindCode
      val byteLength = pigeonVar_list[2] as Long
      val receivedUtcEpochMilliseconds = pigeonVar_list[3] as Long
      val expiresUtcEpochMilliseconds = pigeonVar_list[4] as Long
      return InboundShareDescriptorReply(id, kind, byteLength, receivedUtcEpochMilliseconds, expiresUtcEpochMilliseconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      kind,
      byteLength,
      receivedUtcEpochMilliseconds,
      expiresUtcEpochMilliseconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboundShareDescriptorReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.id, other.id) && KeyBridgeMessagesPigeonUtils.deepEquals(this.kind, other.kind) && KeyBridgeMessagesPigeonUtils.deepEquals(this.byteLength, other.byteLength) && KeyBridgeMessagesPigeonUtils.deepEquals(this.receivedUtcEpochMilliseconds, other.receivedUtcEpochMilliseconds) && KeyBridgeMessagesPigeonUtils.deepEquals(this.expiresUtcEpochMilliseconds, other.expiresUtcEpochMilliseconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.byteLength)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.receivedUtcEpochMilliseconds)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.expiresUtcEpochMilliseconds)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InboundShareListReply (
  val items: List<InboundShareDescriptorReply>,
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboundShareListReply {
      val items = pigeonVar_list[0] as List<InboundShareDescriptorReply>
      val error = pigeonVar_list[1] as PlatformFeatureErrorCode?
      return InboundShareListReply(items, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboundShareListReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.items, other.items) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.items)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InboundShareChunkRequest (
  val id: String,
  val offset: Long,
  val maximumBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboundShareChunkRequest {
      val id = pigeonVar_list[0] as String
      val offset = pigeonVar_list[1] as Long
      val maximumBytes = pigeonVar_list[2] as Long
      return InboundShareChunkRequest(id, offset, maximumBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      offset,
      maximumBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboundShareChunkRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.id, other.id) && KeyBridgeMessagesPigeonUtils.deepEquals(this.offset, other.offset) && KeyBridgeMessagesPigeonUtils.deepEquals(this.maximumBytes, other.maximumBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.offset)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.maximumBytes)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InboundShareChunkReply (
  val bytes: ByteArray,
  val done: Boolean,
  val error: PlatformFeatureErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboundShareChunkReply {
      val bytes = pigeonVar_list[0] as ByteArray
      val done = pigeonVar_list[1] as Boolean
      val error = pigeonVar_list[2] as PlatformFeatureErrorCode?
      return InboundShareChunkReply(bytes, done, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bytes,
      done,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboundShareChunkReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.bytes, other.bytes) && KeyBridgeMessagesPigeonUtils.deepEquals(this.done, other.done) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.bytes)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.done)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}
private open class KeyBridgeMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyBridgeErrorCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformFeatureErrorCode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NotificationPermissionCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WallClockResolutionCode.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ShareKindCode.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateVaultKeyRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenVaultSessionRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RewrapVaultKeyRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptPayloadRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptPayloadRequest.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VaultSessionReply.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayloadReply.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusReply.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecoveryCeremonyReply.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfirmRecoveryKeyRequest.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenVaultWithRecoveryRequest.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SensitiveClipboardRequest.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricStatusReply.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FeatureStatusReply.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationPermissionReply.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LauncherActionReply.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallClockRequest.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallClockReply.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SafeReminderRequest.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboundShareDescriptorReply.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboundShareListReply.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboundShareChunkRequest.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboundShareChunkReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KeyBridgeErrorCode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformFeatureErrorCode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NotificationPermissionCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is WallClockResolutionCode -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ShareKindCode -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is CreateVaultKeyRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is OpenVaultSessionRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is RewrapVaultKeyRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is EncryptPayloadRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is DecryptPayloadRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is VaultSessionReply -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PayloadReply -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is StatusReply -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is RecoveryCeremonyReply -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ConfirmRecoveryKeyRequest -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is OpenVaultWithRecoveryRequest -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is SensitiveClipboardRequest -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is BiometricStatusReply -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is FeatureStatusReply -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is NotificationPermissionReply -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is LauncherActionReply -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is WallClockRequest -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is WallClockReply -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is SafeReminderRequest -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is InboundShareDescriptorReply -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is InboundShareListReply -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is InboundShareChunkRequest -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is InboundShareChunkReply -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KeyBridgeHostApi {
  fun createVaultKey(request: CreateVaultKeyRequest): VaultSessionReply
  fun openVaultSession(request: OpenVaultSessionRequest): VaultSessionReply
  fun encryptPayload(request: EncryptPayloadRequest): PayloadReply
  fun decryptPayload(request: DecryptPayloadRequest): PayloadReply
  fun rewrapVaultKey(request: RewrapVaultKeyRequest): PayloadReply
  fun beginRecoveryKey(sessionHandle: String): RecoveryCeremonyReply
  fun presentRecoveryKey(ceremonyHandle: String): StatusReply
  fun confirmRecoveryKey(request: ConfirmRecoveryKeyRequest): PayloadReply
  fun openVaultWithRecovery(request: OpenVaultWithRecoveryRequest): VaultSessionReply
  fun cancelRecoveryKey(ceremonyHandle: String): StatusReply
  fun setVaultPrivacyActive(active: Boolean): StatusReply
  fun copySensitiveClipboard(request: SensitiveClipboardRequest): StatusReply
  fun clearSensitiveClipboard(): StatusReply
  suspend fun enableBiometric(sessionHandle: String): StatusReply
  suspend fun openVaultWithBiometric(vaultId: String): VaultSessionReply
  suspend fun disableBiometric(sessionHandle: String): StatusReply
  fun biometricStatus(vaultId: String): BiometricStatusReply
  suspend fun notificationPermissionStatus(): NotificationPermissionReply
  suspend fun requestNotificationPermission(): NotificationPermissionReply
  fun openNotificationSettings(): FeatureStatusReply
  fun resolveWallClock(request: WallClockRequest): WallClockReply
  suspend fun replaceReminder(request: SafeReminderRequest): FeatureStatusReply
  fun cancelReminder(syntheticId: String): FeatureStatusReply
  fun installLauncherShortcuts(): FeatureStatusReply
  fun consumeLauncherAction(): LauncherActionReply
  fun listInboundShares(): InboundShareListReply
  fun readInboundShareChunk(request: InboundShareChunkRequest): InboundShareChunkReply
  fun deleteInboundShare(id: String): FeatureStatusReply
  fun purgeExpiredInboundShares(nowUtcEpochMilliseconds: Long): FeatureStatusReply
  fun excludePathFromBackup(absolutePath: String): StatusReply
  fun closeSession(sessionHandle: String): StatusReply
  fun closeAllSessions(): StatusReply

  companion object {
    /** The codec used by KeyBridgeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      KeyBridgeMessagesPigeonCodec()
    }
    /** Sets up an instance of `KeyBridgeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KeyBridgeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.createVaultKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CreateVaultKeyRequest
            val wrapped: List<Any?> = try {
              listOf(api.createVaultKey(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultSession$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OpenVaultSessionRequest
            val wrapped: List<Any?> = try {
              listOf(api.openVaultSession(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.encryptPayload$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EncryptPayloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.encryptPayload(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.decryptPayload$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DecryptPayloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.decryptPayload(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.rewrapVaultKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RewrapVaultKeyRequest
            val wrapped: List<Any?> = try {
              listOf(api.rewrapVaultKey(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.beginRecoveryKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.beginRecoveryKey(sessionHandleArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.presentRecoveryKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ceremonyHandleArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.presentRecoveryKey(ceremonyHandleArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.confirmRecoveryKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ConfirmRecoveryKeyRequest
            val wrapped: List<Any?> = try {
              listOf(api.confirmRecoveryKey(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithRecovery$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OpenVaultWithRecoveryRequest
            val wrapped: List<Any?> = try {
              listOf(api.openVaultWithRecovery(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.cancelRecoveryKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ceremonyHandleArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.cancelRecoveryKey(ceremonyHandleArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.setVaultPrivacyActive$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val activeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.setVaultPrivacyActive(activeArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.copySensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SensitiveClipboardRequest
            val wrapped: List<Any?> = try {
              listOf(api.copySensitiveClipboard(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.clearSensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.clearSensitiveClipboard())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.enableBiometric$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.enableBiometric(sessionHandleArg))
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithBiometric$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val vaultIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.openVaultWithBiometric(vaultIdArg))
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.disableBiometric$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.disableBiometric(sessionHandleArg))
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.biometricStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val vaultIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.biometricStatus(vaultIdArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.notificationPermissionStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.notificationPermissionStatus())
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestNotificationPermission())
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openNotificationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openNotificationSettings())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.resolveWallClock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as WallClockRequest
            val wrapped: List<Any?> = try {
              listOf(api.resolveWallClock(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.replaceReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SafeReminderRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.replaceReminder(requestArg))
              } catch (exception: Throwable) {
                KeyBridgeMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.cancelReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val syntheticIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.cancelReminder(syntheticIdArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.installLauncherShortcuts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.installLauncherShortcuts())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.consumeLauncherAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.consumeLauncherAction())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.listInboundShares$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listInboundShares())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.readInboundShareChunk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InboundShareChunkRequest
            val wrapped: List<Any?> = try {
              listOf(api.readInboundShareChunk(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.deleteInboundShare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteInboundShare(idArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.purgeExpiredInboundShares$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nowUtcEpochMillisecondsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.purgeExpiredInboundShares(nowUtcEpochMillisecondsArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.excludePathFromBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absolutePathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.excludePathFromBackup(absolutePathArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.closeSession(sessionHandleArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeAllSessions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.closeAllSessions())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
