# SPDX-License-Identifier: MPL-2.0
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:lints/recommended.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    prefer_final_locals: true
    unawaited_futures: true
