// SPDX-License-Identifier: MPL-2.0

import 'package:localhold_app_foundation/localhold_app_foundation.dart';
import 'package:localhold_vault_core/localhold_vault_core.dart';

String localizedTemplateFieldLabel(
  LocalholdLocalizations strings,
  String typeId,
  VaultField field,
) => localizedTemplateFieldStableLabel(
  strings,
  typeId,
  field.definitionId,
  field.label,
);

String localizedTemplateFieldStableLabel(
  LocalholdLocalizations strings,
  String typeId,
  String? definitionId,
  String fallback,
) {
  if (!strings.localeName.toLowerCase().startsWith('ru')) return fallback;
  return _ruOverrides['$typeId:$definitionId'] ??
      _ruByStableId[definitionId] ??
      fallback;
}

const _ruOverrides = <String, String>{
  '${BuiltInRecordTypes.paymentCard}:holder': 'Владелец карты',
  '${BuiltInRecordTypes.bankDetails}:holder': 'Владелец счёта',
  '${BuiltInRecordTypes.paymentCard}:number': 'Номер карты',
  '${BuiltInRecordTypes.identityDocument}:number': 'Номер документа',
  '${BuiltInRecordTypes.bankDetails}:account': 'Номер счёта',
  '${BuiltInRecordTypes.softwareLicense}:account': 'Аккаунт или почта лицензии',
  '${BuiltInRecordTypes.router}:endpoint': 'Адрес панели управления',
  '${BuiltInRecordTypes.paymentCard}:issuer': 'Банк-эмитент',
  '${BuiltInRecordTypes.identityDocument}:issuer': 'Кем выдан',
};

const _ruByStableId = <String, String>{
  'title': 'Название',
  'username': 'Имя пользователя',
  'email': 'Электронная почта',
  'password': 'Пароль',
  'website': 'Сайт',
  'account_id': 'ID аккаунта',
  'recovery_email': 'Почта для восстановления',
  'recovery_phone': 'Телефон для восстановления',
  'notes': 'Заметки',
  'service': 'Сервис',
  'profile_name': 'Имя профиля',
  'handle': 'Имя пользователя или ник',
  'profile_url': 'Ссылка на профиль',
  'login_email': 'Почта для входа',
  'login_phone': 'Телефон для входа',
  'recovery_contact': 'Контакт для восстановления',
  'provider': 'Провайдер',
  'app_password': 'Пароль приложения',
  'incoming_server': 'Сервер входящей почты',
  'incoming_port': 'Порт входящей почты',
  'incoming_security': 'Защита входящей почты',
  'outgoing_server': 'Сервер исходящей почты',
  'outgoing_port': 'Порт исходящей почты',
  'outgoing_security': 'Защита исходящей почты',
  'platform': 'Платформа',
  'nickname': 'Ник',
  'login': 'Логин',
  'player_id': 'ID игрока',
  'linked_email': 'Привязанная почта',
  'region': 'Регион',
  'recovery_codes': 'Коды восстановления',
  'amount': 'Сумма',
  'currency': 'Валюта',
  'cadence': 'Период оплаты',
  'first_payment': 'Первая оплата',
  'next_payment': 'Следующая оплата',
  'status': 'Статус',
  'auto_renew': 'Автоматическое продление',
  'trial_end': 'Окончание пробного периода',
  'paid_through': 'Оплачено до',
  'cancelled_at': 'Дата отмены',
  'payment_label': 'Способ оплаты',
  'holder': 'Владелец',
  'number': 'Номер',
  'expiry': 'Срок действия',
  'issuer': 'Эмитент',
  'network': 'Платёжная система',
  'label': 'Название карты',
  'pin': 'PIN',
  'bank': 'Банк',
  'account': 'Аккаунт',
  'iban': 'IBAN',
  'routing': 'Код маршрутизации',
  'bic': 'BIC',
  'swift': 'SWIFT',
  'correspondent_account': 'Корреспондентский счёт',
  'purpose': 'Назначение платежа',
  'reference': 'Комментарий к платежу',
  'full_name': 'Полное имя',
  'phone': 'Телефон',
  'address': 'Адрес',
  'identifiers': 'Идентификаторы',
  'document_type': 'Тип документа',
  'country': 'Страна',
  'issued': 'Дата выдачи',
  'expires': 'Дата окончания',
  'birth_place': 'Место рождения',
  'personal_identifier': 'Личный идентификатор',
  'body': 'Заметка',
  'product': 'Продукт',
  'license_key': 'Лицензионный ключ',
  'edition': 'Редакция',
  'version': 'Версия',
  'seats': 'Количество мест',
  'purchased': 'Дата покупки',
  'download_url': 'Ссылка для скачивания',
  'ssid': 'Название сети',
  'security': 'Тип защиты',
  'hidden': 'Скрытая сеть',
  'admin_url': 'Ссылка на роутер или панель',
  'endpoint': 'Адрес',
  'device': 'Устройство',
  'host': 'Хост',
  'panel_url': 'Панель управления',
  'ssh_user': 'Пользователь SSH',
  'auth_type': 'Способ аутентификации',
  'ssh_key': 'Приватный ключ SSH',
  'port': 'Порт',
  'engine': 'Система базы данных',
  'database': 'Название базы данных',
  'ssl': 'Использовать SSL',
  'token': 'Токен или ключ',
  'secret': 'Секрет',
  'environment': 'Окружение',
  'scopes': 'Разрешения',
  'fingerprint': 'Отпечаток',
  'subtype': 'Тип',
  'public_material': 'Публичный ключ или сертификат',
  'private_key': 'Приватный ключ',
  'passphrase': 'Кодовая фраза',
  'valid_from': 'Действует с',
  'valid_until': 'Действует до',
  'codes': 'Коды восстановления',
  'generated': 'Дата создания',
  'account_name': 'Название аккаунта',
  'public_address': 'Публичный адрес',
  'seed_phrase': 'Сид-фраза',
};
