// SPDX-License-Identifier: MPL-2.0
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum KeyBridgeErrorCode {
  invalidRequest,
  invalidCredentials,
  unsupportedVersion,
  sessionNotFound,
  sessionLocked,
  integrityFailure,
  payloadTooLarge,
  platformUnavailable,
  notImplemented,
  internalFailure,
}

class CreateVaultKeyRequest {
  CreateVaultKeyRequest({required this.masterPassword});

  Uint8List masterPassword;

  List<Object?> _toList() {
    return <Object?>[masterPassword];
  }

  Object encode() {
    return _toList();
  }

  static CreateVaultKeyRequest decode(Object result) {
    result as List<Object?>;
    return CreateVaultKeyRequest(masterPassword: result[0]! as Uint8List);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateVaultKeyRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(masterPassword, other.masterPassword);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class OpenVaultSessionRequest {
  OpenVaultSessionRequest({
    required this.masterPassword,
    required this.vaultKeyEnvelope,
  });

  Uint8List masterPassword;

  Uint8List vaultKeyEnvelope;

  List<Object?> _toList() {
    return <Object?>[masterPassword, vaultKeyEnvelope];
  }

  Object encode() {
    return _toList();
  }

  static OpenVaultSessionRequest decode(Object result) {
    result as List<Object?>;
    return OpenVaultSessionRequest(
      masterPassword: result[0]! as Uint8List,
      vaultKeyEnvelope: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenVaultSessionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(masterPassword, other.masterPassword) &&
        _deepEquals(vaultKeyEnvelope, other.vaultKeyEnvelope);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class RewrapVaultKeyRequest {
  RewrapVaultKeyRequest({
    required this.sessionHandle,
    required this.newMasterPassword,
  });

  String sessionHandle;

  Uint8List newMasterPassword;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, newMasterPassword];
  }

  Object encode() {
    return _toList();
  }

  static RewrapVaultKeyRequest decode(Object result) {
    result as List<Object?>;
    return RewrapVaultKeyRequest(
      sessionHandle: result[0]! as String,
      newMasterPassword: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RewrapVaultKeyRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(newMasterPassword, other.newMasterPassword);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class EncryptPayloadRequest {
  EncryptPayloadRequest({
    required this.sessionHandle,
    required this.plaintext,
    required this.authenticatedData,
  });

  String sessionHandle;

  Uint8List plaintext;

  Uint8List authenticatedData;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, plaintext, authenticatedData];
  }

  Object encode() {
    return _toList();
  }

  static EncryptPayloadRequest decode(Object result) {
    result as List<Object?>;
    return EncryptPayloadRequest(
      sessionHandle: result[0]! as String,
      plaintext: result[1]! as Uint8List,
      authenticatedData: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EncryptPayloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(plaintext, other.plaintext) &&
        _deepEquals(authenticatedData, other.authenticatedData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class DecryptPayloadRequest {
  DecryptPayloadRequest({
    required this.sessionHandle,
    required this.encryptedPayload,
    required this.authenticatedData,
  });

  String sessionHandle;

  Uint8List encryptedPayload;

  Uint8List authenticatedData;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, encryptedPayload, authenticatedData];
  }

  Object encode() {
    return _toList();
  }

  static DecryptPayloadRequest decode(Object result) {
    result as List<Object?>;
    return DecryptPayloadRequest(
      sessionHandle: result[0]! as String,
      encryptedPayload: result[1]! as Uint8List,
      authenticatedData: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptPayloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(encryptedPayload, other.encryptedPayload) &&
        _deepEquals(authenticatedData, other.authenticatedData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class VaultSessionReply {
  VaultSessionReply({this.sessionHandle, this.vaultKeyEnvelope, this.error});

  String? sessionHandle;

  Uint8List? vaultKeyEnvelope;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, vaultKeyEnvelope, error];
  }

  Object encode() {
    return _toList();
  }

  static VaultSessionReply decode(Object result) {
    result as List<Object?>;
    return VaultSessionReply(
      sessionHandle: result[0] as String?,
      vaultKeyEnvelope: result[1] as Uint8List?,
      error: result[2] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VaultSessionReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(vaultKeyEnvelope, other.vaultKeyEnvelope) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class PayloadReply {
  PayloadReply({this.payload, this.error});

  Uint8List? payload;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[payload, error];
  }

  Object encode() {
    return _toList();
  }

  static PayloadReply decode(Object result) {
    result as List<Object?>;
    return PayloadReply(
      payload: result[0] as Uint8List?,
      error: result[1] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayloadReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(payload, other.payload) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class StatusReply {
  StatusReply({this.error});

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static StatusReply decode(Object result) {
    result as List<Object?>;
    return StatusReply(error: result[0] as KeyBridgeErrorCode?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StatusReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is KeyBridgeErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CreateVaultKeyRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is OpenVaultSessionRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RewrapVaultKeyRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is EncryptPayloadRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is DecryptPayloadRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is VaultSessionReply) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PayloadReply) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is StatusReply) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyBridgeErrorCode.values[value];
      case 130:
        return CreateVaultKeyRequest.decode(readValue(buffer)!);
      case 131:
        return OpenVaultSessionRequest.decode(readValue(buffer)!);
      case 132:
        return RewrapVaultKeyRequest.decode(readValue(buffer)!);
      case 133:
        return EncryptPayloadRequest.decode(readValue(buffer)!);
      case 134:
        return DecryptPayloadRequest.decode(readValue(buffer)!);
      case 135:
        return VaultSessionReply.decode(readValue(buffer)!);
      case 136:
        return PayloadReply.decode(readValue(buffer)!);
      case 137:
        return StatusReply.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KeyBridgeHostApi {
  /// Constructor for [KeyBridgeHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KeyBridgeHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VaultSessionReply> createVaultKey(
    CreateVaultKeyRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.createVaultKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<VaultSessionReply> openVaultSession(
    OpenVaultSessionRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.openVaultSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<PayloadReply> encryptPayload(EncryptPayloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.encryptPayload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<PayloadReply> decryptPayload(DecryptPayloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.decryptPayload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<PayloadReply> rewrapVaultKey(RewrapVaultKeyRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.rewrapVaultKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<StatusReply> closeSession(String sessionHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.closeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> closeAllSessions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.closeAllSessions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }
}
