// SPDX-License-Identifier: MPL-2.0
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.localhold.localhold_key_bridge

import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object KeyBridgeMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  @Suppress("UNUSED_PARAMETER")
  fun wrapError(exception: Throwable): List<Any?> {
    return listOf("internalFailure", null, null)
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class KeyBridgeErrorCode(val raw: Int) {
  INVALID_REQUEST(0),
  INVALID_CREDENTIALS(1),
  UNSUPPORTED_VERSION(2),
  SESSION_NOT_FOUND(3),
  SESSION_LOCKED(4),
  INTEGRITY_FAILURE(5),
  PAYLOAD_TOO_LARGE(6),
  PLATFORM_UNAVAILABLE(7),
  NOT_IMPLEMENTED(8),
  INTERNAL_FAILURE(9);

  companion object {
    fun ofRaw(raw: Int): KeyBridgeErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateVaultKeyRequest (
  val masterPassword: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateVaultKeyRequest {
      val masterPassword = pigeonVar_list[0] as ByteArray
      return CreateVaultKeyRequest(masterPassword)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      masterPassword,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateVaultKeyRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.masterPassword, other.masterPassword)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.masterPassword)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenVaultSessionRequest (
  val masterPassword: ByteArray,
  val vaultKeyEnvelope: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenVaultSessionRequest {
      val masterPassword = pigeonVar_list[0] as ByteArray
      val vaultKeyEnvelope = pigeonVar_list[1] as ByteArray
      return OpenVaultSessionRequest(masterPassword, vaultKeyEnvelope)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      masterPassword,
      vaultKeyEnvelope,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenVaultSessionRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.masterPassword, other.masterPassword) && KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultKeyEnvelope, other.vaultKeyEnvelope)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.masterPassword)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultKeyEnvelope)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RewrapVaultKeyRequest (
  val sessionHandle: String,
  val newMasterPassword: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RewrapVaultKeyRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val newMasterPassword = pigeonVar_list[1] as ByteArray
      return RewrapVaultKeyRequest(sessionHandle, newMasterPassword)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      newMasterPassword,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RewrapVaultKeyRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.newMasterPassword, other.newMasterPassword)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.newMasterPassword)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EncryptPayloadRequest (
  val sessionHandle: String,
  val plaintext: ByteArray,
  val authenticatedData: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EncryptPayloadRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val plaintext = pigeonVar_list[1] as ByteArray
      val authenticatedData = pigeonVar_list[2] as ByteArray
      return EncryptPayloadRequest(sessionHandle, plaintext, authenticatedData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      plaintext,
      authenticatedData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EncryptPayloadRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.plaintext, other.plaintext) && KeyBridgeMessagesPigeonUtils.deepEquals(this.authenticatedData, other.authenticatedData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.plaintext)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.authenticatedData)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptPayloadRequest (
  val sessionHandle: String,
  val encryptedPayload: ByteArray,
  val authenticatedData: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptPayloadRequest {
      val sessionHandle = pigeonVar_list[0] as String
      val encryptedPayload = pigeonVar_list[1] as ByteArray
      val authenticatedData = pigeonVar_list[2] as ByteArray
      return DecryptPayloadRequest(sessionHandle, encryptedPayload, authenticatedData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      encryptedPayload,
      authenticatedData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DecryptPayloadRequest
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.encryptedPayload, other.encryptedPayload) && KeyBridgeMessagesPigeonUtils.deepEquals(this.authenticatedData, other.authenticatedData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.encryptedPayload)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.authenticatedData)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VaultSessionReply (
  val sessionHandle: String? = null,
  val vaultKeyEnvelope: ByteArray? = null,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VaultSessionReply {
      val sessionHandle = pigeonVar_list[0] as String?
      val vaultKeyEnvelope = pigeonVar_list[1] as ByteArray?
      val error = pigeonVar_list[2] as KeyBridgeErrorCode?
      return VaultSessionReply(sessionHandle, vaultKeyEnvelope, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionHandle,
      vaultKeyEnvelope,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VaultSessionReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.sessionHandle, other.sessionHandle) && KeyBridgeMessagesPigeonUtils.deepEquals(this.vaultKeyEnvelope, other.vaultKeyEnvelope) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.sessionHandle)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.vaultKeyEnvelope)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PayloadReply (
  val payload: ByteArray? = null,
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayloadReply {
      val payload = pigeonVar_list[0] as ByteArray?
      val error = pigeonVar_list[1] as KeyBridgeErrorCode?
      return PayloadReply(payload, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PayloadReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.payload, other.payload) && KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.payload)
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StatusReply (
  val error: KeyBridgeErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusReply {
      val error = pigeonVar_list[0] as KeyBridgeErrorCode?
      return StatusReply(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatusReply
    return KeyBridgeMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyBridgeMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "KeyBridgeMessage(<redacted>)"
  }
}
private open class KeyBridgeMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyBridgeErrorCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateVaultKeyRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenVaultSessionRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RewrapVaultKeyRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptPayloadRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptPayloadRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VaultSessionReply.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayloadReply.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KeyBridgeErrorCode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CreateVaultKeyRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OpenVaultSessionRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RewrapVaultKeyRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is EncryptPayloadRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DecryptPayloadRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VaultSessionReply -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PayloadReply -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is StatusReply -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KeyBridgeHostApi {
  fun createVaultKey(request: CreateVaultKeyRequest): VaultSessionReply
  fun openVaultSession(request: OpenVaultSessionRequest): VaultSessionReply
  fun encryptPayload(request: EncryptPayloadRequest): PayloadReply
  fun decryptPayload(request: DecryptPayloadRequest): PayloadReply
  fun rewrapVaultKey(request: RewrapVaultKeyRequest): PayloadReply
  fun closeSession(sessionHandle: String): StatusReply
  fun closeAllSessions(): StatusReply

  companion object {
    /** The codec used by KeyBridgeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      KeyBridgeMessagesPigeonCodec()
    }
    /** Sets up an instance of `KeyBridgeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KeyBridgeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.createVaultKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CreateVaultKeyRequest
            val wrapped: List<Any?> = try {
              listOf(api.createVaultKey(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.openVaultSession$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OpenVaultSessionRequest
            val wrapped: List<Any?> = try {
              listOf(api.openVaultSession(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.encryptPayload$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EncryptPayloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.encryptPayload(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.decryptPayload$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DecryptPayloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.decryptPayload(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.rewrapVaultKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RewrapVaultKeyRequest
            val wrapped: List<Any?> = try {
              listOf(api.rewrapVaultKey(requestArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.closeSession(sessionHandleArg))
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.localhold_key_bridge.KeyBridgeHostApi.closeAllSessions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.closeAllSessions())
            } catch (exception: Throwable) {
              KeyBridgeMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
