// SPDX-License-Identifier: MPL-2.0

import 'models.dart';

abstract final class BuiltInTemplateCatalog {
  static final List<RecordTypeDefinition> all = List.unmodifiable([
    _type(
      BuiltInRecordTypes.account,
      'Account',
      TemplateCategory.accounts,
      TemplateIcon.account,
      [
        _title(),
        _field('username', VaultFieldKind.username, 'Username', display: true),
        _field('email', VaultFieldKind.email, 'Email', display: true),
        _secret('password', 'Password'),
        _field('website', VaultFieldKind.url, 'Website', display: true),
        _field(
          'account_id',
          VaultFieldKind.text,
          'Account ID',
          protected: true,
        ),
        _field(
          'recovery_email',
          VaultFieldKind.email,
          'Recovery email',
          protected: true,
          section: FieldSection.advanced,
        ),
        _field(
          'recovery_phone',
          VaultFieldKind.phone,
          'Recovery phone',
          protected: true,
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.socialProfile,
      'Social network',
      TemplateCategory.accounts,
      TemplateIcon.social,
      [
        _title(),
        _field('service', VaultFieldKind.text, 'Service', display: true),
        _field(
          'profile_name',
          VaultFieldKind.text,
          'Profile name',
          display: true,
        ),
        _field(
          'handle',
          VaultFieldKind.username,
          'Username or handle',
          display: true,
        ),
        _field('profile_url', VaultFieldKind.url, 'Profile URL', display: true),
        _field(
          'login_email',
          VaultFieldKind.email,
          'Login email',
          protected: true,
        ),
        _field(
          'login_phone',
          VaultFieldKind.phone,
          'Login phone',
          protected: true,
        ),
        _secret('password', 'Password'),
        _field(
          'account_id',
          VaultFieldKind.text,
          'Account ID',
          protected: true,
        ),
        _field(
          'recovery_contact',
          VaultFieldKind.text,
          'Recovery contact',
          protected: true,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.emailAccount,
      'Email account',
      TemplateCategory.accounts,
      TemplateIcon.email,
      [
        _title(),
        _field('provider', VaultFieldKind.text, 'Provider', display: true),
        _field('email', VaultFieldKind.email, 'Email', display: true),
        _secret('password', 'Password'),
        _secret('app_password', 'App password', section: FieldSection.details),
        _field(
          'recovery_email',
          VaultFieldKind.email,
          'Recovery email',
          protected: true,
        ),
        _field(
          'recovery_phone',
          VaultFieldKind.phone,
          'Recovery phone',
          protected: true,
        ),
        _field(
          'incoming_server',
          VaultFieldKind.text,
          'Incoming server',
          section: FieldSection.advanced,
        ),
        _field(
          'incoming_port',
          VaultFieldKind.number,
          'Incoming port',
          section: FieldSection.advanced,
        ),
        _field(
          'incoming_security',
          VaultFieldKind.choice,
          'Incoming security',
          section: FieldSection.advanced,
        ),
        _field(
          'outgoing_server',
          VaultFieldKind.text,
          'Outgoing server',
          section: FieldSection.advanced,
        ),
        _field(
          'outgoing_port',
          VaultFieldKind.number,
          'Outgoing port',
          section: FieldSection.advanced,
        ),
        _field(
          'outgoing_security',
          VaultFieldKind.choice,
          'Outgoing security',
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.gamingAccount,
      'Gaming account',
      TemplateCategory.accounts,
      TemplateIcon.gaming,
      [
        _title(),
        _field('platform', VaultFieldKind.text, 'Platform', display: true),
        _field('nickname', VaultFieldKind.text, 'Nickname', display: true),
        _field('login', VaultFieldKind.username, 'Login', display: true),
        _secret('password', 'Password'),
        _field('player_id', VaultFieldKind.text, 'Player ID', display: true),
        _field(
          'linked_email',
          VaultFieldKind.email,
          'Linked email',
          display: true,
        ),
        _field('region', VaultFieldKind.text, 'Region'),
        _field('profile_url', VaultFieldKind.url, 'Profile URL', display: true),
        _secret(
          'recovery_codes',
          'Recovery codes',
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.subscription,
      'Subscription',
      TemplateCategory.money,
      TemplateIcon.subscription,
      [
        _title(),
        _field('provider', VaultFieldKind.text, 'Provider', display: true),
        _field(
          'amount',
          VaultFieldKind.money,
          'Amount',
          search: FieldSearchScope.none,
        ),
        _field(
          'currency',
          VaultFieldKind.currency,
          'Currency',
          search: FieldSearchScope.none,
        ),
        _field('cadence', VaultFieldKind.period, 'Billing period'),
        _field(
          'first_payment',
          VaultFieldKind.date,
          'First payment',
          search: FieldSearchScope.none,
        ),
        _field(
          'next_payment',
          VaultFieldKind.date,
          'Next payment',
          search: FieldSearchScope.none,
        ),
        _field('status', VaultFieldKind.choice, 'Status'),
        _field(
          'auto_renew',
          VaultFieldKind.boolean,
          'Renews automatically',
          search: FieldSearchScope.none,
        ),
        _field(
          'trial_end',
          VaultFieldKind.date,
          'Trial ends',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field(
          'paid_through',
          VaultFieldKind.date,
          'Paid through',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field(
          'cancelled_at',
          VaultFieldKind.date,
          'Cancellation date',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field('website', VaultFieldKind.url, 'Website', display: true),
        _field(
          'payment_label',
          VaultFieldKind.text,
          'Payment method label',
          protected: true,
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.paymentCard,
      'Bank card',
      TemplateCategory.money,
      TemplateIcon.paymentCard,
      [
        _title(),
        _field('holder', VaultFieldKind.text, 'Cardholder', display: true),
        _secret('number', 'Card number'),
        _field(
          'expiry',
          VaultFieldKind.date,
          'Expiry',
          protected: true,
          search: FieldSearchScope.none,
        ),
        _field('issuer', VaultFieldKind.text, 'Issuer', display: true),
        _field('network', VaultFieldKind.choice, 'Payment network'),
        _field('label', VaultFieldKind.text, 'Card label', display: true),
        _secret('pin', 'PIN', warning: 'do_not_store_card_pin'),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.bankDetails,
      'Bank details',
      TemplateCategory.money,
      TemplateIcon.bank,
      [
        _title(),
        _field('holder', VaultFieldKind.text, 'Account holder', display: true),
        _field('bank', VaultFieldKind.text, 'Bank', display: true),
        _secret('account', 'Account number'),
        _secret('iban', 'IBAN'),
        _field(
          'routing',
          VaultFieldKind.text,
          'Routing number',
          protected: true,
        ),
        _field('bic', VaultFieldKind.text, 'BIC', protected: true),
        _field('swift', VaultFieldKind.text, 'SWIFT', protected: true),
        _secret(
          'correspondent_account',
          'Correspondent account',
          section: FieldSection.advanced,
        ),
        _field(
          'purpose',
          VaultFieldKind.note,
          'Payment purpose',
          protected: true,
          section: FieldSection.advanced,
        ),
        _field(
          'reference',
          VaultFieldKind.text,
          'Payment reference',
          protected: true,
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.identity,
      'Personal contact or identity',
      TemplateCategory.personal,
      TemplateIcon.identity,
      [
        _title(),
        _field('full_name', VaultFieldKind.text, 'Full name', display: true),
        _field('phone', VaultFieldKind.phone, 'Phone', display: true),
        _field('email', VaultFieldKind.email, 'Email', display: true),
        _field('address', VaultFieldKind.address, 'Address', protected: true),
        _field(
          'identifiers',
          VaultFieldKind.note,
          'Identifiers',
          protected: true,
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.identityDocument,
      'Passport or document',
      TemplateCategory.personal,
      TemplateIcon.document,
      [
        _title(),
        _field(
          'document_type',
          VaultFieldKind.choice,
          'Document type',
          display: true,
        ),
        _field('country', VaultFieldKind.text, 'Country'),
        _field('full_name', VaultFieldKind.text, 'Full name', display: true),
        _secret('number', 'Document number'),
        _field(
          'issued',
          VaultFieldKind.date,
          'Issue date',
          search: FieldSearchScope.none,
        ),
        _field(
          'expires',
          VaultFieldKind.date,
          'Expiry date',
          search: FieldSearchScope.none,
        ),
        _field('issuer', VaultFieldKind.text, 'Issuer'),
        _field(
          'birth_place',
          VaultFieldKind.text,
          'Place of birth',
          protected: true,
          section: FieldSection.advanced,
        ),
        _secret(
          'personal_identifier',
          'Personal identifier',
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.secureNote,
      'Secure note',
      TemplateCategory.personal,
      TemplateIcon.secureNote,
      [_title(), _field('body', VaultFieldKind.note, 'Note', protected: true)],
    ),
    _type(
      BuiltInRecordTypes.softwareLicense,
      'Software license',
      TemplateCategory.technical,
      TemplateIcon.software,
      [
        _title(),
        _field('product', VaultFieldKind.text, 'Product', display: true),
        _secret('license_key', 'License key'),
        _field(
          'account',
          VaultFieldKind.email,
          'Licensed account or email',
          display: true,
        ),
        _field('edition', VaultFieldKind.text, 'Edition'),
        _field('version', VaultFieldKind.text, 'Version'),
        _field(
          'seats',
          VaultFieldKind.number,
          'Seats',
          search: FieldSearchScope.none,
        ),
        _field(
          'purchased',
          VaultFieldKind.date,
          'Purchase date',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field(
          'expires',
          VaultFieldKind.date,
          'Expiry date',
          search: FieldSearchScope.none,
        ),
        _field('download_url', VaultFieldKind.url, 'Download URL'),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.wirelessNetwork,
      'Wi-Fi',
      TemplateCategory.technical,
      TemplateIcon.wifi,
      [
        _title(),
        _field('ssid', VaultFieldKind.text, 'Network name', display: true),
        _secret('password', 'Password'),
        _field('security', VaultFieldKind.choice, 'Security type'),
        _field(
          'hidden',
          VaultFieldKind.boolean,
          'Hidden network',
          search: FieldSearchScope.none,
        ),
        _field(
          'admin_url',
          VaultFieldKind.url,
          'Router or admin link',
          protected: true,
          section: FieldSection.advanced,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.router,
      'Router',
      TemplateCategory.technical,
      TemplateIcon.router,
      [
        _title(),
        _field('endpoint', VaultFieldKind.url, 'Admin address', display: true),
        _field('username', VaultFieldKind.username, 'Username', display: true),
        _secret('password', 'Password'),
        _field('device', VaultFieldKind.text, 'Device', display: true),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.server,
      'Server or hosting',
      TemplateCategory.technical,
      TemplateIcon.server,
      [
        _title(),
        _field('host', VaultFieldKind.text, 'Host', display: true),
        _field('provider', VaultFieldKind.text, 'Provider', display: true),
        _field('panel_url', VaultFieldKind.url, 'Control panel'),
        _field('ssh_user', VaultFieldKind.username, 'SSH user', display: true),
        _field('auth_type', VaultFieldKind.choice, 'Authentication type'),
        _secret('password', 'Password'),
        _secret('ssh_key', 'SSH private key', section: FieldSection.advanced),
        _field(
          'port',
          VaultFieldKind.number,
          'Port',
          search: FieldSearchScope.none,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.database,
      'Database',
      TemplateCategory.technical,
      TemplateIcon.database,
      [
        _title(),
        _field(
          'engine',
          VaultFieldKind.choice,
          'Database engine',
          display: true,
        ),
        _field('host', VaultFieldKind.text, 'Host', display: true),
        _field(
          'port',
          VaultFieldKind.number,
          'Port',
          search: FieldSearchScope.none,
        ),
        _field('database', VaultFieldKind.text, 'Database name', display: true),
        _field('username', VaultFieldKind.username, 'Username', display: true),
        _secret('password', 'Password'),
        _field(
          'ssl',
          VaultFieldKind.boolean,
          'Use SSL',
          search: FieldSearchScope.none,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.apiCredential,
      'API key or token',
      TemplateCategory.technical,
      TemplateIcon.api,
      [
        _title(),
        _field('service', VaultFieldKind.text, 'Service', display: true),
        _secret('token', 'Token or key'),
        _secret('secret', 'Secret'),
        _field(
          'environment',
          VaultFieldKind.choice,
          'Environment',
          display: true,
        ),
        _field('scopes', VaultFieldKind.note, 'Scopes', protected: true),
        _field('endpoint', VaultFieldKind.url, 'Endpoint', display: true),
        _field(
          'issued',
          VaultFieldKind.date,
          'Issue date',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field(
          'expires',
          VaultFieldKind.date,
          'Expiry date',
          search: FieldSearchScope.none,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.sshCredential,
      'SSH key or certificate',
      TemplateCategory.technical,
      TemplateIcon.ssh,
      [
        _title(),
        _field('subtype', VaultFieldKind.choice, 'Type', display: true),
        _field(
          'public_material',
          VaultFieldKind.note,
          'Public key or certificate',
          search: FieldSearchScope.none,
        ),
        _field(
          'fingerprint',
          VaultFieldKind.text,
          'Fingerprint',
          display: true,
        ),
        _field('host', VaultFieldKind.text, 'Host', display: true),
        _field('username', VaultFieldKind.username, 'Username', display: true),
        _secret('private_key', 'Private key'),
        _secret('passphrase', 'Passphrase'),
        _field(
          'issuer',
          VaultFieldKind.text,
          'Issuer',
          section: FieldSection.advanced,
        ),
        _field(
          'valid_from',
          VaultFieldKind.date,
          'Valid from',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _field(
          'valid_until',
          VaultFieldKind.date,
          'Valid until',
          section: FieldSection.advanced,
          search: FieldSearchScope.none,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.recoveryCodes,
      'Recovery codes',
      TemplateCategory.technical,
      TemplateIcon.recovery,
      [
        _title(),
        _field('service', VaultFieldKind.text, 'Service', display: true),
        _field('account', VaultFieldKind.username, 'Account', display: true),
        _secret('codes', 'Recovery codes'),
        _field(
          'generated',
          VaultFieldKind.date,
          'Generated date',
          search: FieldSearchScope.none,
        ),
        _notes(),
      ],
    ),
    _type(
      BuiltInRecordTypes.cryptoAccount,
      'Cryptocurrency account',
      TemplateCategory.technical,
      TemplateIcon.crypto,
      [
        _title(),
        _field('service', VaultFieldKind.text, 'Service', display: true),
        _field(
          'account_name',
          VaultFieldKind.text,
          'Account name',
          display: true,
        ),
        _field('username', VaultFieldKind.username, 'Username', display: true),
        _field(
          'public_address',
          VaultFieldKind.text,
          'Public address',
          protected: true,
        ),
        _secret(
          'seed_phrase',
          'Seed phrase',
          warning: 'localhold_is_not_a_wallet',
        ),
        _secret(
          'private_key',
          'Private key',
          warning: 'localhold_is_not_a_wallet',
        ),
        _field('website', VaultFieldKind.url, 'Website', display: true),
        _notes(),
      ],
    ),
  ]);

  static RecordTypeDefinition? byStableId(String stableId) {
    for (final definition in all) {
      if (definition.stableId == stableId) return definition;
    }
    return null;
  }

  static List<RecordTypeDefinition> inCategory(TemplateCategory category) =>
      List.unmodifiable(
        all.where((definition) => definition.category == category),
      );

  static RecordTypeDefinition _type(
    String id,
    String name,
    TemplateCategory category,
    TemplateIcon icon,
    List<FieldDefinition> fields,
  ) => RecordTypeDefinition(
    stableId: id,
    defaultName: name,
    category: category,
    icon: icon,
    fields: fields,
  );

  static FieldDefinition _title() =>
      _field('title', VaultFieldKind.text, 'Title', display: true);

  static FieldDefinition _notes() => _field(
    'notes',
    VaultFieldKind.note,
    'Notes',
    protected: true,
    section: FieldSection.advanced,
  );

  static FieldDefinition _secret(
    String id,
    String label, {
    FieldSection section = FieldSection.details,
    String? warning,
  }) => _field(
    id,
    VaultFieldKind.secret,
    label,
    protected: true,
    section: section,
    warning: warning,
  );

  static FieldDefinition _field(
    String id,
    VaultFieldKind kind,
    String label, {
    bool protected = false,
    bool display = false,
    FieldSection section = FieldSection.primary,
    FieldSearchScope? search,
    String? warning,
  }) => FieldDefinition(
    stableId: id,
    kind: kind,
    defaultLabel: label,
    protected: protected,
    displayCandidate: display,
    section: section,
    searchScope: search,
    warningCode: warning,
  );
}
