// SPDX-License-Identifier: MPL-2.0
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum KeyBridgeErrorCode {
  invalidRequest,
  invalidCredentials,
  unsupportedVersion,
  sessionNotFound,
  sessionLocked,
  reauthenticationRequired,
  integrityFailure,
  payloadTooLarge,
  platformUnavailable,
  biometricUnavailable,
  biometricInvalidated,
  internalFailure,
}

enum PlatformFeatureErrorCode {
  invalidRequest,
  permissionDenied,
  permissionRestricted,
  notFound,
  platformUnavailable,
  internalFailure,
}

enum NotificationPermissionCode {
  notDetermined,
  denied,
  restricted,
  authorized,
}

enum WallClockResolutionCode { unique, earlier, later, gapAdjusted }

enum ShareKindCode { text, url, file, image }

class CreateVaultKeyRequest {
  CreateVaultKeyRequest({required this.vaultId, required this.masterPassword});

  String vaultId;

  Uint8List masterPassword;

  List<Object?> _toList() {
    return <Object?>[vaultId, masterPassword];
  }

  Object encode() {
    return _toList();
  }

  static CreateVaultKeyRequest decode(Object result) {
    result as List<Object?>;
    return CreateVaultKeyRequest(
      vaultId: result[0]! as String,
      masterPassword: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateVaultKeyRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(vaultId, other.vaultId) &&
        _deepEquals(masterPassword, other.masterPassword);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class OpenVaultSessionRequest {
  OpenVaultSessionRequest({
    required this.vaultId,
    required this.masterPassword,
    required this.vaultKeyEnvelope,
  });

  String vaultId;

  Uint8List masterPassword;

  Uint8List vaultKeyEnvelope;

  List<Object?> _toList() {
    return <Object?>[vaultId, masterPassword, vaultKeyEnvelope];
  }

  Object encode() {
    return _toList();
  }

  static OpenVaultSessionRequest decode(Object result) {
    result as List<Object?>;
    return OpenVaultSessionRequest(
      vaultId: result[0]! as String,
      masterPassword: result[1]! as Uint8List,
      vaultKeyEnvelope: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenVaultSessionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(vaultId, other.vaultId) &&
        _deepEquals(masterPassword, other.masterPassword) &&
        _deepEquals(vaultKeyEnvelope, other.vaultKeyEnvelope);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class RewrapVaultKeyRequest {
  RewrapVaultKeyRequest({
    required this.sessionHandle,
    required this.newMasterPassword,
  });

  String sessionHandle;

  Uint8List newMasterPassword;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, newMasterPassword];
  }

  Object encode() {
    return _toList();
  }

  static RewrapVaultKeyRequest decode(Object result) {
    result as List<Object?>;
    return RewrapVaultKeyRequest(
      sessionHandle: result[0]! as String,
      newMasterPassword: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RewrapVaultKeyRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(newMasterPassword, other.newMasterPassword);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class EncryptPayloadRequest {
  EncryptPayloadRequest({
    required this.sessionHandle,
    required this.plaintext,
    required this.authenticatedData,
  });

  String sessionHandle;

  Uint8List plaintext;

  Uint8List authenticatedData;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, plaintext, authenticatedData];
  }

  Object encode() {
    return _toList();
  }

  static EncryptPayloadRequest decode(Object result) {
    result as List<Object?>;
    return EncryptPayloadRequest(
      sessionHandle: result[0]! as String,
      plaintext: result[1]! as Uint8List,
      authenticatedData: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EncryptPayloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(plaintext, other.plaintext) &&
        _deepEquals(authenticatedData, other.authenticatedData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class DecryptPayloadRequest {
  DecryptPayloadRequest({
    required this.sessionHandle,
    required this.encryptedPayload,
    required this.authenticatedData,
  });

  String sessionHandle;

  Uint8List encryptedPayload;

  Uint8List authenticatedData;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, encryptedPayload, authenticatedData];
  }

  Object encode() {
    return _toList();
  }

  static DecryptPayloadRequest decode(Object result) {
    result as List<Object?>;
    return DecryptPayloadRequest(
      sessionHandle: result[0]! as String,
      encryptedPayload: result[1]! as Uint8List,
      authenticatedData: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptPayloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(encryptedPayload, other.encryptedPayload) &&
        _deepEquals(authenticatedData, other.authenticatedData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class VaultSessionReply {
  VaultSessionReply({
    this.sessionHandle,
    this.keyGenerationId,
    this.vaultKeyEnvelope,
    this.error,
  });

  String? sessionHandle;

  String? keyGenerationId;

  Uint8List? vaultKeyEnvelope;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[sessionHandle, keyGenerationId, vaultKeyEnvelope, error];
  }

  Object encode() {
    return _toList();
  }

  static VaultSessionReply decode(Object result) {
    result as List<Object?>;
    return VaultSessionReply(
      sessionHandle: result[0] as String?,
      keyGenerationId: result[1] as String?,
      vaultKeyEnvelope: result[2] as Uint8List?,
      error: result[3] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VaultSessionReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionHandle, other.sessionHandle) &&
        _deepEquals(keyGenerationId, other.keyGenerationId) &&
        _deepEquals(vaultKeyEnvelope, other.vaultKeyEnvelope) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class PayloadReply {
  PayloadReply({this.payload, this.error});

  Uint8List? payload;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[payload, error];
  }

  Object encode() {
    return _toList();
  }

  static PayloadReply decode(Object result) {
    result as List<Object?>;
    return PayloadReply(
      payload: result[0] as Uint8List?,
      error: result[1] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayloadReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(payload, other.payload) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class StatusReply {
  StatusReply({this.error});

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static StatusReply decode(Object result) {
    result as List<Object?>;
    return StatusReply(error: result[0] as KeyBridgeErrorCode?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StatusReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class RecoveryCeremonyReply {
  RecoveryCeremonyReply({
    this.ceremonyHandle,
    this.challengePositions,
    this.error,
  });

  String? ceremonyHandle;

  List<int>? challengePositions;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[ceremonyHandle, challengePositions, error];
  }

  Object encode() {
    return _toList();
  }

  static RecoveryCeremonyReply decode(Object result) {
    result as List<Object?>;
    return RecoveryCeremonyReply(
      ceremonyHandle: result[0] as String?,
      challengePositions: (result[1] as List<Object?>?)?.cast<int>(),
      error: result[2] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecoveryCeremonyReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ceremonyHandle, other.ceremonyHandle) &&
        _deepEquals(challengePositions, other.challengePositions) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class ConfirmRecoveryKeyRequest {
  ConfirmRecoveryKeyRequest({
    required this.ceremonyHandle,
    required this.challengeWordsUtf8,
  });

  String ceremonyHandle;

  Uint8List challengeWordsUtf8;

  List<Object?> _toList() {
    return <Object?>[ceremonyHandle, challengeWordsUtf8];
  }

  Object encode() {
    return _toList();
  }

  static ConfirmRecoveryKeyRequest decode(Object result) {
    result as List<Object?>;
    return ConfirmRecoveryKeyRequest(
      ceremonyHandle: result[0]! as String,
      challengeWordsUtf8: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfirmRecoveryKeyRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ceremonyHandle, other.ceremonyHandle) &&
        _deepEquals(challengeWordsUtf8, other.challengeWordsUtf8);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class OpenVaultWithRecoveryRequest {
  OpenVaultWithRecoveryRequest({
    required this.vaultId,
    required this.recoveryPhraseUtf8,
    required this.recoveryKeyEnvelope,
  });

  String vaultId;

  Uint8List recoveryPhraseUtf8;

  Uint8List recoveryKeyEnvelope;

  List<Object?> _toList() {
    return <Object?>[vaultId, recoveryPhraseUtf8, recoveryKeyEnvelope];
  }

  Object encode() {
    return _toList();
  }

  static OpenVaultWithRecoveryRequest decode(Object result) {
    result as List<Object?>;
    return OpenVaultWithRecoveryRequest(
      vaultId: result[0]! as String,
      recoveryPhraseUtf8: result[1]! as Uint8List,
      recoveryKeyEnvelope: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenVaultWithRecoveryRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(vaultId, other.vaultId) &&
        _deepEquals(recoveryPhraseUtf8, other.recoveryPhraseUtf8) &&
        _deepEquals(recoveryKeyEnvelope, other.recoveryKeyEnvelope);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class SensitiveClipboardRequest {
  SensitiveClipboardRequest({
    required this.utf8Value,
    required this.expirySeconds,
  });

  Uint8List utf8Value;

  int expirySeconds;

  List<Object?> _toList() {
    return <Object?>[utf8Value, expirySeconds];
  }

  Object encode() {
    return _toList();
  }

  static SensitiveClipboardRequest decode(Object result) {
    result as List<Object?>;
    return SensitiveClipboardRequest(
      utf8Value: result[0]! as Uint8List,
      expirySeconds: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SensitiveClipboardRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(utf8Value, other.utf8Value) &&
        _deepEquals(expirySeconds, other.expirySeconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class BiometricStatusReply {
  BiometricStatusReply({
    required this.configured,
    this.invalidated = false,
    this.error,
  });

  bool configured;

  bool invalidated;

  KeyBridgeErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[configured, invalidated, error];
  }

  Object encode() {
    return _toList();
  }

  static BiometricStatusReply decode(Object result) {
    result as List<Object?>;
    return BiometricStatusReply(
      configured: result[0]! as bool,
      invalidated: result[1]! as bool,
      error: result[2] as KeyBridgeErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BiometricStatusReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(configured, other.configured) &&
        _deepEquals(invalidated, other.invalidated) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class FeatureStatusReply {
  FeatureStatusReply({this.error});

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static FeatureStatusReply decode(Object result) {
    result as List<Object?>;
    return FeatureStatusReply(error: result[0] as PlatformFeatureErrorCode?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FeatureStatusReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class NotificationPermissionReply {
  NotificationPermissionReply({required this.state, this.error});

  NotificationPermissionCode state;

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[state, error];
  }

  Object encode() {
    return _toList();
  }

  static NotificationPermissionReply decode(Object result) {
    result as List<Object?>;
    return NotificationPermissionReply(
      state: result[0]! as NotificationPermissionCode,
      error: result[1] as PlatformFeatureErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationPermissionReply ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class LauncherActionReply {
  LauncherActionReply({required this.actionCode, this.error});

  int actionCode;

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[actionCode, error];
  }

  Object encode() {
    return _toList();
  }

  static LauncherActionReply decode(Object result) {
    result as List<Object?>;
    return LauncherActionReply(
      actionCode: result[0]! as int,
      error: result[1] as PlatformFeatureErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LauncherActionReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(actionCode, other.actionCode) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class WallClockRequest {
  WallClockRequest({
    required this.year,
    required this.month,
    required this.day,
    required this.hour,
    required this.minute,
    required this.timeZoneId,
  });

  int year;

  int month;

  int day;

  int hour;

  int minute;

  String timeZoneId;

  List<Object?> _toList() {
    return <Object?>[year, month, day, hour, minute, timeZoneId];
  }

  Object encode() {
    return _toList();
  }

  static WallClockRequest decode(Object result) {
    result as List<Object?>;
    return WallClockRequest(
      year: result[0]! as int,
      month: result[1]! as int,
      day: result[2]! as int,
      hour: result[3]! as int,
      minute: result[4]! as int,
      timeZoneId: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WallClockRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) &&
        _deepEquals(month, other.month) &&
        _deepEquals(day, other.day) &&
        _deepEquals(hour, other.hour) &&
        _deepEquals(minute, other.minute) &&
        _deepEquals(timeZoneId, other.timeZoneId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class WallClockReply {
  WallClockReply({
    required this.utcEpochMilliseconds,
    required this.resolution,
    this.error,
  });

  int utcEpochMilliseconds;

  WallClockResolutionCode resolution;

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[utcEpochMilliseconds, resolution, error];
  }

  Object encode() {
    return _toList();
  }

  static WallClockReply decode(Object result) {
    result as List<Object?>;
    return WallClockReply(
      utcEpochMilliseconds: result[0]! as int,
      resolution: result[1]! as WallClockResolutionCode,
      error: result[2] as PlatformFeatureErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WallClockReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(utcEpochMilliseconds, other.utcEpochMilliseconds) &&
        _deepEquals(resolution, other.resolution) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class SafeReminderRequest {
  SafeReminderRequest({
    required this.syntheticId,
    required this.utcEpochMilliseconds,
    required this.privacyCode,
    this.safeName,
    this.safeAmount,
  });

  String syntheticId;

  int utcEpochMilliseconds;

  int privacyCode;

  String? safeName;

  String? safeAmount;

  List<Object?> _toList() {
    return <Object?>[
      syntheticId,
      utcEpochMilliseconds,
      privacyCode,
      safeName,
      safeAmount,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SafeReminderRequest decode(Object result) {
    result as List<Object?>;
    return SafeReminderRequest(
      syntheticId: result[0]! as String,
      utcEpochMilliseconds: result[1]! as int,
      privacyCode: result[2]! as int,
      safeName: result[3] as String?,
      safeAmount: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SafeReminderRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(syntheticId, other.syntheticId) &&
        _deepEquals(utcEpochMilliseconds, other.utcEpochMilliseconds) &&
        _deepEquals(privacyCode, other.privacyCode) &&
        _deepEquals(safeName, other.safeName) &&
        _deepEquals(safeAmount, other.safeAmount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class InboundShareDescriptorReply {
  InboundShareDescriptorReply({
    required this.id,
    required this.kind,
    required this.byteLength,
    required this.receivedUtcEpochMilliseconds,
    required this.expiresUtcEpochMilliseconds,
  });

  String id;

  ShareKindCode kind;

  int byteLength;

  int receivedUtcEpochMilliseconds;

  int expiresUtcEpochMilliseconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      byteLength,
      receivedUtcEpochMilliseconds,
      expiresUtcEpochMilliseconds,
    ];
  }

  Object encode() {
    return _toList();
  }

  static InboundShareDescriptorReply decode(Object result) {
    result as List<Object?>;
    return InboundShareDescriptorReply(
      id: result[0]! as String,
      kind: result[1]! as ShareKindCode,
      byteLength: result[2]! as int,
      receivedUtcEpochMilliseconds: result[3]! as int,
      expiresUtcEpochMilliseconds: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboundShareDescriptorReply ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(byteLength, other.byteLength) &&
        _deepEquals(
          receivedUtcEpochMilliseconds,
          other.receivedUtcEpochMilliseconds,
        ) &&
        _deepEquals(
          expiresUtcEpochMilliseconds,
          other.expiresUtcEpochMilliseconds,
        );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class InboundShareListReply {
  InboundShareListReply({required this.items, this.error});

  List<InboundShareDescriptorReply> items;

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[items, error];
  }

  Object encode() {
    return _toList();
  }

  static InboundShareListReply decode(Object result) {
    result as List<Object?>;
    return InboundShareListReply(
      items: (result[0]! as List<Object?>).cast<InboundShareDescriptorReply>(),
      error: result[1] as PlatformFeatureErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboundShareListReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(items, other.items) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class InboundShareChunkRequest {
  InboundShareChunkRequest({
    required this.id,
    required this.offset,
    required this.maximumBytes,
  });

  String id;

  int offset;

  int maximumBytes;

  List<Object?> _toList() {
    return <Object?>[id, offset, maximumBytes];
  }

  Object encode() {
    return _toList();
  }

  static InboundShareChunkRequest decode(Object result) {
    result as List<Object?>;
    return InboundShareChunkRequest(
      id: result[0]! as String,
      offset: result[1]! as int,
      maximumBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboundShareChunkRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(offset, other.offset) &&
        _deepEquals(maximumBytes, other.maximumBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class InboundShareChunkReply {
  InboundShareChunkReply({required this.bytes, required this.done, this.error});

  Uint8List bytes;

  bool done;

  PlatformFeatureErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[bytes, done, error];
  }

  Object encode() {
    return _toList();
  }

  static InboundShareChunkReply decode(Object result) {
    result as List<Object?>;
    return InboundShareChunkReply(
      bytes: result[0]! as Uint8List,
      done: result[1]! as bool,
      error: result[2] as PlatformFeatureErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboundShareChunkReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bytes, other.bytes) &&
        _deepEquals(done, other.done) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyBridgeMessage(<redacted>)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is KeyBridgeErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformFeatureErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NotificationPermissionCode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is WallClockResolutionCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is ShareKindCode) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is CreateVaultKeyRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is OpenVaultSessionRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is RewrapVaultKeyRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is EncryptPayloadRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is DecryptPayloadRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is VaultSessionReply) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PayloadReply) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is StatusReply) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is RecoveryCeremonyReply) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is ConfirmRecoveryKeyRequest) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is OpenVaultWithRecoveryRequest) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is SensitiveClipboardRequest) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is BiometricStatusReply) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is FeatureStatusReply) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is NotificationPermissionReply) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is LauncherActionReply) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is WallClockRequest) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is WallClockReply) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is SafeReminderRequest) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is InboundShareDescriptorReply) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is InboundShareListReply) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is InboundShareChunkRequest) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is InboundShareChunkReply) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyBridgeErrorCode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformFeatureErrorCode.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NotificationPermissionCode.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : WallClockResolutionCode.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : ShareKindCode.values[value];
      case 134:
        return CreateVaultKeyRequest.decode(readValue(buffer)!);
      case 135:
        return OpenVaultSessionRequest.decode(readValue(buffer)!);
      case 136:
        return RewrapVaultKeyRequest.decode(readValue(buffer)!);
      case 137:
        return EncryptPayloadRequest.decode(readValue(buffer)!);
      case 138:
        return DecryptPayloadRequest.decode(readValue(buffer)!);
      case 139:
        return VaultSessionReply.decode(readValue(buffer)!);
      case 140:
        return PayloadReply.decode(readValue(buffer)!);
      case 141:
        return StatusReply.decode(readValue(buffer)!);
      case 142:
        return RecoveryCeremonyReply.decode(readValue(buffer)!);
      case 143:
        return ConfirmRecoveryKeyRequest.decode(readValue(buffer)!);
      case 144:
        return OpenVaultWithRecoveryRequest.decode(readValue(buffer)!);
      case 145:
        return SensitiveClipboardRequest.decode(readValue(buffer)!);
      case 146:
        return BiometricStatusReply.decode(readValue(buffer)!);
      case 147:
        return FeatureStatusReply.decode(readValue(buffer)!);
      case 148:
        return NotificationPermissionReply.decode(readValue(buffer)!);
      case 149:
        return LauncherActionReply.decode(readValue(buffer)!);
      case 150:
        return WallClockRequest.decode(readValue(buffer)!);
      case 151:
        return WallClockReply.decode(readValue(buffer)!);
      case 152:
        return SafeReminderRequest.decode(readValue(buffer)!);
      case 153:
        return InboundShareDescriptorReply.decode(readValue(buffer)!);
      case 154:
        return InboundShareListReply.decode(readValue(buffer)!);
      case 155:
        return InboundShareChunkRequest.decode(readValue(buffer)!);
      case 156:
        return InboundShareChunkReply.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KeyBridgeHostApi {
  /// Constructor for [KeyBridgeHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KeyBridgeHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VaultSessionReply> createVaultKey(
    CreateVaultKeyRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.createVaultKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<VaultSessionReply> openVaultSession(
    OpenVaultSessionRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<PayloadReply> encryptPayload(EncryptPayloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.encryptPayload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<PayloadReply> decryptPayload(DecryptPayloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.decryptPayload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<PayloadReply> rewrapVaultKey(RewrapVaultKeyRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.rewrapVaultKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<RecoveryCeremonyReply> beginRecoveryKey(String sessionHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.beginRecoveryKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RecoveryCeremonyReply;
  }

  Future<StatusReply> presentRecoveryKey(String ceremonyHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.presentRecoveryKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ceremonyHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<PayloadReply> confirmRecoveryKey(
    ConfirmRecoveryKeyRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.confirmRecoveryKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PayloadReply;
  }

  Future<VaultSessionReply> openVaultWithRecovery(
    OpenVaultWithRecoveryRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithRecovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<StatusReply> cancelRecoveryKey(String ceremonyHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.cancelRecoveryKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ceremonyHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> setVaultPrivacyActive(bool active) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.setVaultPrivacyActive$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[active],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> copySensitiveClipboard(
    SensitiveClipboardRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.copySensitiveClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> clearSensitiveClipboard() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.clearSensitiveClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> enableBiometric(String sessionHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.enableBiometric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<VaultSessionReply> openVaultWithBiometric(String vaultId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithBiometric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[vaultId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VaultSessionReply;
  }

  Future<StatusReply> disableBiometric(String sessionHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.disableBiometric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<BiometricStatusReply> biometricStatus(String vaultId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.biometricStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[vaultId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BiometricStatusReply;
  }

  Future<NotificationPermissionReply> notificationPermissionStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.notificationPermissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NotificationPermissionReply;
  }

  Future<NotificationPermissionReply> requestNotificationPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NotificationPermissionReply;
  }

  Future<FeatureStatusReply> openNotificationSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openNotificationSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<WallClockReply> resolveWallClock(WallClockRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.resolveWallClock$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WallClockReply;
  }

  Future<FeatureStatusReply> replaceReminder(
    SafeReminderRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.replaceReminder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<FeatureStatusReply> cancelReminder(String syntheticId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.cancelReminder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[syntheticId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<FeatureStatusReply> installLauncherShortcuts() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.installLauncherShortcuts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<LauncherActionReply> consumeLauncherAction() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.consumeLauncherAction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as LauncherActionReply;
  }

  Future<InboundShareListReply> listInboundShares() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.listInboundShares$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as InboundShareListReply;
  }

  Future<InboundShareChunkReply> readInboundShareChunk(
    InboundShareChunkRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.readInboundShareChunk$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as InboundShareChunkReply;
  }

  Future<FeatureStatusReply> deleteInboundShare(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.deleteInboundShare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<FeatureStatusReply> purgeExpiredInboundShares(
    int nowUtcEpochMilliseconds,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.purgeExpiredInboundShares$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[nowUtcEpochMilliseconds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureStatusReply;
  }

  Future<StatusReply> excludePathFromBackup(String absolutePath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.excludePathFromBackup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absolutePath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> closeSession(String sessionHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }

  Future<StatusReply> closeAllSessions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeAllSessions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StatusReply;
  }
}
