// SPDX-License-Identifier: MPL-2.0
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  _ = error
  return ["internalFailure", nil, nil]
}

enum KeyBridgeMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum KeyBridgeErrorCode: Int, CaseIterable {
  case invalidRequest = 0
  case invalidCredentials = 1
  case unsupportedVersion = 2
  case sessionNotFound = 3
  case sessionLocked = 4
  case reauthenticationRequired = 5
  case integrityFailure = 6
  case payloadTooLarge = 7
  case platformUnavailable = 8
  case biometricUnavailable = 9
  case biometricInvalidated = 10
  case internalFailure = 11
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreateVaultKeyRequest: Hashable, CustomStringConvertible {
  var vaultId: String
  var masterPassword: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateVaultKeyRequest? {
    let vaultId = pigeonVar_list[0] as! String
    let masterPassword = pigeonVar_list[1] as! FlutterStandardTypedData

    return CreateVaultKeyRequest(
      vaultId: vaultId,
      masterPassword: masterPassword
    )
  }
  func toList() -> [Any?] {
    return [
      vaultId,
      masterPassword,
    ]
  }
  static func == (lhs: CreateVaultKeyRequest, rhs: CreateVaultKeyRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.vaultId, rhs.vaultId) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.masterPassword, rhs.masterPassword)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreateVaultKeyRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: vaultId, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: masterPassword, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenVaultSessionRequest: Hashable, CustomStringConvertible {
  var vaultId: String
  var masterPassword: FlutterStandardTypedData
  var vaultKeyEnvelope: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenVaultSessionRequest? {
    let vaultId = pigeonVar_list[0] as! String
    let masterPassword = pigeonVar_list[1] as! FlutterStandardTypedData
    let vaultKeyEnvelope = pigeonVar_list[2] as! FlutterStandardTypedData

    return OpenVaultSessionRequest(
      vaultId: vaultId,
      masterPassword: masterPassword,
      vaultKeyEnvelope: vaultKeyEnvelope
    )
  }
  func toList() -> [Any?] {
    return [
      vaultId,
      masterPassword,
      vaultKeyEnvelope,
    ]
  }
  static func == (lhs: OpenVaultSessionRequest, rhs: OpenVaultSessionRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.vaultId, rhs.vaultId) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.masterPassword, rhs.masterPassword) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.vaultKeyEnvelope, rhs.vaultKeyEnvelope)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenVaultSessionRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: vaultId, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: masterPassword, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: vaultKeyEnvelope, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RewrapVaultKeyRequest: Hashable, CustomStringConvertible {
  var sessionHandle: String
  var newMasterPassword: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RewrapVaultKeyRequest? {
    let sessionHandle = pigeonVar_list[0] as! String
    let newMasterPassword = pigeonVar_list[1] as! FlutterStandardTypedData

    return RewrapVaultKeyRequest(
      sessionHandle: sessionHandle,
      newMasterPassword: newMasterPassword
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      newMasterPassword,
    ]
  }
  static func == (lhs: RewrapVaultKeyRequest, rhs: RewrapVaultKeyRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.newMasterPassword, rhs.newMasterPassword)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RewrapVaultKeyRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: newMasterPassword, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EncryptPayloadRequest: Hashable, CustomStringConvertible {
  var sessionHandle: String
  var plaintext: FlutterStandardTypedData
  var authenticatedData: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EncryptPayloadRequest? {
    let sessionHandle = pigeonVar_list[0] as! String
    let plaintext = pigeonVar_list[1] as! FlutterStandardTypedData
    let authenticatedData = pigeonVar_list[2] as! FlutterStandardTypedData

    return EncryptPayloadRequest(
      sessionHandle: sessionHandle,
      plaintext: plaintext,
      authenticatedData: authenticatedData
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      plaintext,
      authenticatedData,
    ]
  }
  static func == (lhs: EncryptPayloadRequest, rhs: EncryptPayloadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.plaintext, rhs.plaintext) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.authenticatedData, rhs.authenticatedData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EncryptPayloadRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: plaintext, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: authenticatedData, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptPayloadRequest: Hashable, CustomStringConvertible {
  var sessionHandle: String
  var encryptedPayload: FlutterStandardTypedData
  var authenticatedData: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptPayloadRequest? {
    let sessionHandle = pigeonVar_list[0] as! String
    let encryptedPayload = pigeonVar_list[1] as! FlutterStandardTypedData
    let authenticatedData = pigeonVar_list[2] as! FlutterStandardTypedData

    return DecryptPayloadRequest(
      sessionHandle: sessionHandle,
      encryptedPayload: encryptedPayload,
      authenticatedData: authenticatedData
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      encryptedPayload,
      authenticatedData,
    ]
  }
  static func == (lhs: DecryptPayloadRequest, rhs: DecryptPayloadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.encryptedPayload, rhs.encryptedPayload) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.authenticatedData, rhs.authenticatedData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DecryptPayloadRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: encryptedPayload, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: authenticatedData, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VaultSessionReply: Hashable, CustomStringConvertible {
  var sessionHandle: String? = nil
  var keyGenerationId: String? = nil
  var vaultKeyEnvelope: FlutterStandardTypedData? = nil
  var error: KeyBridgeErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VaultSessionReply? {
    let sessionHandle: String? = nilOrValue(pigeonVar_list[0])
    let keyGenerationId: String? = nilOrValue(pigeonVar_list[1])
    let vaultKeyEnvelope: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let error: KeyBridgeErrorCode? = nilOrValue(pigeonVar_list[3])

    return VaultSessionReply(
      sessionHandle: sessionHandle,
      keyGenerationId: keyGenerationId,
      vaultKeyEnvelope: vaultKeyEnvelope,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      keyGenerationId,
      vaultKeyEnvelope,
      error,
    ]
  }
  static func == (lhs: VaultSessionReply, rhs: VaultSessionReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.keyGenerationId, rhs.keyGenerationId) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.vaultKeyEnvelope, rhs.vaultKeyEnvelope) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VaultSessionReply")
    KeyBridgeMessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: keyGenerationId, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: vaultKeyEnvelope, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PayloadReply: Hashable, CustomStringConvertible {
  var payload: FlutterStandardTypedData? = nil
  var error: KeyBridgeErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PayloadReply? {
    let payload: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let error: KeyBridgeErrorCode? = nilOrValue(pigeonVar_list[1])

    return PayloadReply(
      payload: payload,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      payload,
      error,
    ]
  }
  static func == (lhs: PayloadReply, rhs: PayloadReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PayloadReply")
    KeyBridgeMessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StatusReply: Hashable, CustomStringConvertible {
  var error: KeyBridgeErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StatusReply? {
    let error: KeyBridgeErrorCode? = nilOrValue(pigeonVar_list[0])

    return StatusReply(
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      error
    ]
  }
  static func == (lhs: StatusReply, rhs: StatusReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StatusReply")
    KeyBridgeMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecoveryCeremonyReply: Hashable, CustomStringConvertible {
  var ceremonyHandle: String? = nil
  var challengePositions: [Int64]? = nil
  var error: KeyBridgeErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecoveryCeremonyReply? {
    let ceremonyHandle: String? = nilOrValue(pigeonVar_list[0])
    let challengePositions: [Int64]? = nilOrValue(pigeonVar_list[1])
    let error: KeyBridgeErrorCode? = nilOrValue(pigeonVar_list[2])

    return RecoveryCeremonyReply(
      ceremonyHandle: ceremonyHandle,
      challengePositions: challengePositions,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      ceremonyHandle,
      challengePositions,
      error,
    ]
  }
  static func == (lhs: RecoveryCeremonyReply, rhs: RecoveryCeremonyReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.ceremonyHandle, rhs.ceremonyHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.challengePositions, rhs.challengePositions) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecoveryCeremonyReply")
    KeyBridgeMessagesPigeonInternal.deepHash(value: ceremonyHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: challengePositions, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfirmRecoveryKeyRequest: Hashable, CustomStringConvertible {
  var ceremonyHandle: String
  var challengeWordsUtf8: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfirmRecoveryKeyRequest? {
    let ceremonyHandle = pigeonVar_list[0] as! String
    let challengeWordsUtf8 = pigeonVar_list[1] as! FlutterStandardTypedData

    return ConfirmRecoveryKeyRequest(
      ceremonyHandle: ceremonyHandle,
      challengeWordsUtf8: challengeWordsUtf8
    )
  }
  func toList() -> [Any?] {
    return [
      ceremonyHandle,
      challengeWordsUtf8,
    ]
  }
  static func == (lhs: ConfirmRecoveryKeyRequest, rhs: ConfirmRecoveryKeyRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.ceremonyHandle, rhs.ceremonyHandle) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.challengeWordsUtf8, rhs.challengeWordsUtf8)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConfirmRecoveryKeyRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: ceremonyHandle, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: challengeWordsUtf8, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenVaultWithRecoveryRequest: Hashable, CustomStringConvertible {
  var vaultId: String
  var recoveryPhraseUtf8: FlutterStandardTypedData
  var recoveryKeyEnvelope: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenVaultWithRecoveryRequest? {
    let vaultId = pigeonVar_list[0] as! String
    let recoveryPhraseUtf8 = pigeonVar_list[1] as! FlutterStandardTypedData
    let recoveryKeyEnvelope = pigeonVar_list[2] as! FlutterStandardTypedData

    return OpenVaultWithRecoveryRequest(
      vaultId: vaultId,
      recoveryPhraseUtf8: recoveryPhraseUtf8,
      recoveryKeyEnvelope: recoveryKeyEnvelope
    )
  }
  func toList() -> [Any?] {
    return [
      vaultId,
      recoveryPhraseUtf8,
      recoveryKeyEnvelope,
    ]
  }
  static func == (lhs: OpenVaultWithRecoveryRequest, rhs: OpenVaultWithRecoveryRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.vaultId, rhs.vaultId) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.recoveryPhraseUtf8, rhs.recoveryPhraseUtf8) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.recoveryKeyEnvelope, rhs.recoveryKeyEnvelope)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenVaultWithRecoveryRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: vaultId, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: recoveryPhraseUtf8, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: recoveryKeyEnvelope, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SensitiveClipboardRequest: Hashable, CustomStringConvertible {
  var utf8Value: FlutterStandardTypedData
  var expirySeconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SensitiveClipboardRequest? {
    let utf8Value = pigeonVar_list[0] as! FlutterStandardTypedData
    let expirySeconds = pigeonVar_list[1] as! Int64

    return SensitiveClipboardRequest(
      utf8Value: utf8Value,
      expirySeconds: expirySeconds
    )
  }
  func toList() -> [Any?] {
    return [
      utf8Value,
      expirySeconds,
    ]
  }
  static func == (lhs: SensitiveClipboardRequest, rhs: SensitiveClipboardRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.utf8Value, rhs.utf8Value) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.expirySeconds, rhs.expirySeconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SensitiveClipboardRequest")
    KeyBridgeMessagesPigeonInternal.deepHash(value: utf8Value, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: expirySeconds, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricStatusReply: Hashable, CustomStringConvertible {
  var configured: Bool
  var invalidated: Bool
  var error: KeyBridgeErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricStatusReply? {
    let configured = pigeonVar_list[0] as! Bool
    let invalidated = pigeonVar_list[1] as! Bool
    let error: KeyBridgeErrorCode? = nilOrValue(pigeonVar_list[2])

    return BiometricStatusReply(
      configured: configured,
      invalidated: invalidated,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      configured,
      invalidated,
      error,
    ]
  }
  static func == (lhs: BiometricStatusReply, rhs: BiometricStatusReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return KeyBridgeMessagesPigeonInternal.deepEquals(lhs.configured, rhs.configured) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.invalidated, rhs.invalidated) && KeyBridgeMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BiometricStatusReply")
    KeyBridgeMessagesPigeonInternal.deepHash(value: configured, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: invalidated, hasher: &hasher)
    KeyBridgeMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "KeyBridgeMessage(<redacted>)"
  }
}

private class KeyBridgeMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyBridgeErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CreateVaultKeyRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return OpenVaultSessionRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return RewrapVaultKeyRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return EncryptPayloadRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return DecryptPayloadRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return VaultSessionReply.fromList(self.readValue() as! [Any?])
    case 136:
      return PayloadReply.fromList(self.readValue() as! [Any?])
    case 137:
      return StatusReply.fromList(self.readValue() as! [Any?])
    case 138:
      return RecoveryCeremonyReply.fromList(self.readValue() as! [Any?])
    case 139:
      return ConfirmRecoveryKeyRequest.fromList(self.readValue() as! [Any?])
    case 140:
      return OpenVaultWithRecoveryRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return SensitiveClipboardRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return BiometricStatusReply.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class KeyBridgeMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KeyBridgeErrorCode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CreateVaultKeyRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? OpenVaultSessionRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RewrapVaultKeyRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? EncryptPayloadRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptPayloadRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VaultSessionReply {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PayloadReply {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? StatusReply {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? RecoveryCeremonyReply {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ConfirmRecoveryKeyRequest {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? OpenVaultWithRecoveryRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? SensitiveClipboardRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? BiometricStatusReply {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class KeyBridgeMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return KeyBridgeMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return KeyBridgeMessagesPigeonCodecWriter(data: data)
  }
}

class KeyBridgeMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = KeyBridgeMessagesPigeonCodec(readerWriter: KeyBridgeMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KeyBridgeHostApi {
  func createVaultKey(request: CreateVaultKeyRequest) throws -> VaultSessionReply
  func openVaultSession(request: OpenVaultSessionRequest) throws -> VaultSessionReply
  func encryptPayload(request: EncryptPayloadRequest) throws -> PayloadReply
  func decryptPayload(request: DecryptPayloadRequest) throws -> PayloadReply
  func rewrapVaultKey(request: RewrapVaultKeyRequest) throws -> PayloadReply
  func beginRecoveryKey(sessionHandle: String) throws -> RecoveryCeremonyReply
  func presentRecoveryKey(ceremonyHandle: String) throws -> StatusReply
  func confirmRecoveryKey(request: ConfirmRecoveryKeyRequest) throws -> PayloadReply
  func openVaultWithRecovery(request: OpenVaultWithRecoveryRequest) throws -> VaultSessionReply
  func cancelRecoveryKey(ceremonyHandle: String) throws -> StatusReply
  func setVaultPrivacyActive(active: Bool) throws -> StatusReply
  func copySensitiveClipboard(request: SensitiveClipboardRequest) throws -> StatusReply
  func clearSensitiveClipboard() throws -> StatusReply
  func enableBiometric(sessionHandle: String) async throws -> StatusReply
  func openVaultWithBiometric(vaultId: String) async throws -> VaultSessionReply
  func disableBiometric(sessionHandle: String) async throws -> StatusReply
  func biometricStatus(vaultId: String) throws -> BiometricStatusReply
  func excludePathFromBackup(absolutePath: String) throws -> StatusReply
  func closeSession(sessionHandle: String) throws -> StatusReply
  func closeAllSessions() throws -> StatusReply
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KeyBridgeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { KeyBridgeMessagesPigeonCodec.shared }
  /// Sets up an instance of `KeyBridgeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KeyBridgeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let createVaultKeyChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.createVaultKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.createVaultKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      createVaultKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CreateVaultKeyRequest
        do {
          let result = try api.createVaultKey(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createVaultKeyChannel.setMessageHandler(nil)
    }
    let openVaultSessionChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      openVaultSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OpenVaultSessionRequest
        do {
          let result = try api.openVaultSession(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openVaultSessionChannel.setMessageHandler(nil)
    }
    let encryptPayloadChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.encryptPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.encryptPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      encryptPayloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! EncryptPayloadRequest
        do {
          let result = try api.encryptPayload(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      encryptPayloadChannel.setMessageHandler(nil)
    }
    let decryptPayloadChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.decryptPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.decryptPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      decryptPayloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DecryptPayloadRequest
        do {
          let result = try api.decryptPayload(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      decryptPayloadChannel.setMessageHandler(nil)
    }
    let rewrapVaultKeyChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.rewrapVaultKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.rewrapVaultKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      rewrapVaultKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RewrapVaultKeyRequest
        do {
          let result = try api.rewrapVaultKey(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rewrapVaultKeyChannel.setMessageHandler(nil)
    }
    let beginRecoveryKeyChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.beginRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.beginRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      beginRecoveryKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! String
        do {
          let result = try api.beginRecoveryKey(sessionHandle: sessionHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      beginRecoveryKeyChannel.setMessageHandler(nil)
    }
    let presentRecoveryKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.presentRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentRecoveryKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ceremonyHandleArg = args[0] as! String
        do {
          let result = try api.presentRecoveryKey(ceremonyHandle: ceremonyHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      presentRecoveryKeyChannel.setMessageHandler(nil)
    }
    let confirmRecoveryKeyChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.confirmRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.confirmRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      confirmRecoveryKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ConfirmRecoveryKeyRequest
        do {
          let result = try api.confirmRecoveryKey(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      confirmRecoveryKeyChannel.setMessageHandler(nil)
    }
    let openVaultWithRecoveryChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithRecovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithRecovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      openVaultWithRecoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OpenVaultWithRecoveryRequest
        do {
          let result = try api.openVaultWithRecovery(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openVaultWithRecoveryChannel.setMessageHandler(nil)
    }
    let cancelRecoveryKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.cancelRecoveryKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRecoveryKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ceremonyHandleArg = args[0] as! String
        do {
          let result = try api.cancelRecoveryKey(ceremonyHandle: ceremonyHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRecoveryKeyChannel.setMessageHandler(nil)
    }
    let setVaultPrivacyActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.setVaultPrivacyActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVaultPrivacyActiveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let activeArg = args[0] as! Bool
        do {
          let result = try api.setVaultPrivacyActive(active: activeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVaultPrivacyActiveChannel.setMessageHandler(nil)
    }
    let copySensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.copySensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      copySensitiveClipboardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SensitiveClipboardRequest
        do {
          let result = try api.copySensitiveClipboard(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      copySensitiveClipboardChannel.setMessageHandler(nil)
    }
    let clearSensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.clearSensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSensitiveClipboardChannel.setMessageHandler { _, reply in
        do {
          let result = try api.clearSensitiveClipboard()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSensitiveClipboardChannel.setMessageHandler(nil)
    }
    let enableBiometricChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.enableBiometric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableBiometricChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.enableBiometric(sessionHandle: sessionHandleArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableBiometricChannel.setMessageHandler(nil)
    }
    let openVaultWithBiometricChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.openVaultWithBiometric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openVaultWithBiometricChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.openVaultWithBiometric(vaultId: vaultIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openVaultWithBiometricChannel.setMessageHandler(nil)
    }
    let disableBiometricChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.disableBiometric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableBiometricChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.disableBiometric(sessionHandle: sessionHandleArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disableBiometricChannel.setMessageHandler(nil)
    }
    let biometricStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.biometricStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      biometricStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        do {
          let result = try api.biometricStatus(vaultId: vaultIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      biometricStatusChannel.setMessageHandler(nil)
    }
    let excludePathFromBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.excludePathFromBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      excludePathFromBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let absolutePathArg = args[0] as! String
        do {
          let result = try api.excludePathFromBackup(absolutePath: absolutePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      excludePathFromBackupChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! String
        do {
          let result = try api.closeSession(sessionHandle: sessionHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
    let closeAllSessionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.localhold_vault_native.KeyBridgeHostApi.closeAllSessions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeAllSessionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.closeAllSessions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeAllSessionsChannel.setMessageHandler(nil)
    }
  }
}

// Pigeon 28 does not mark async reply value types Sendable. Swift 6 requires
// this explicit reviewed boundary when results return to the main-actor reply.
extension VaultSessionReply: @unchecked Sendable {}
extension StatusReply: @unchecked Sendable {}
